//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocallyMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocallyDBEntities : DbContext
    {
        public LocallyDBEntities()
            : base("name=LocallyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutContentTable> AboutContentTables { get; set; }
        public virtual DbSet<SlidersTable> SlidersTables { get; set; }
        public virtual DbSet<TeammembersTable> TeammembersTables { get; set; }
    }
}
